# Pandas

In [1]:
1.Create DataFrame
>Using Lists
>Using Dictionary
2.Copy Dataframe
3.Select/Keep columns
4.Create /add new columns
5.Rename Columns
6.Sorting DataFrame
7.Select rows or columns
8.Drop Rows/ Columns
9.Reset/ Set index


10.Filter based on conditional operators
>Using Basic method
>Using query function
11.Missing Data
12.Group by operation
13.Merging Concept : Concatation,Append,Merge,join

SyntaxError: invalid decimal literal (3777549385.py, line 1)

#### Library

In [4]:
#pip install pandas
import pandas as pd

### 1.a Create a DataFrame from Lists

In [5]:
list1=[['a',1],['b',2],['c',3]]
pd.DataFrame(list1,columns=['Number','Character'])

  Number  Character
0      a          1
1      b          2
2      c          3

### 1.b Create a DataFrame from Dict of ndarrays / Lists

In [6]:
Age=[12,15,56,89]
Salary=[6000,7000,8000,9000]
Name=['A','B','C','D']
index=['first','second','third','four']
df=pd.DataFrame({'Name': Name,'Age':Age,'Salary':Salary},index=index)
df

       Name  Age  Salary
first     A   12    6000
second    B   15    7000
third     C   56    8000
four      D   89    9000

### 2.Copy DataFrame

In [7]:
df1=df.copy()
df1

       Name  Age  Salary
first     A   12    6000
second    B   15    7000
third     C   56    8000
four      D   89    9000

### 3.Select/Keep columns

In [8]:
#Dataframe[columnnames]
df['Name']

first     A
second    B
third     C
four      D
Name: Name, dtype: object

In [9]:
df3=df[['Name','Age']]
df3

       Name  Age
first     A   12
second    B   15
third     C   56
four      D   89

### 4.Create /add new columns

In [10]:
df['new']=df['Age']+df['Salary']
df

       Name  Age  Salary   new
first     A   12    6000  6012
second    B   15    7000  7015
third     C   56    8000  8056
four      D   89    9000  9089

### 5.Rename Columns

In [11]:
#inplace=True:overwrite the existing dataset
label={'Name':'Student Name','Age':'Student Age'}
df.rename(columns=label,inplace=True)

In [12]:
df

       Student Name  Student Age  Salary   new
first             A           12    6000  6012
second            B           15    7000  7015
third             C           56    8000  8056
four              D           89    9000  9089

### 6.Sorting DataFrame

DataFrame.sort_values(by, axis=0, ascending=True, inplace=False, kind=’quicksort’, na_position=’last’)

In [13]:
df.sort_values(['Salary','new'],ascending=[False,False],inplace=True)

In [14]:
df

       Student Name  Student Age  Salary   new
four              D           89    9000  9089
third             C           56    8000  8056
second            B           15    7000  7015
first             A           12    6000  6012

### 7.Select Rows/Columns

Select rows using 2 methods: <br>
1.iloc=select row based on index label <br>
2.loc=select row based on index position

In [15]:
df

       Student Name  Student Age  Salary   new
four              D           89    9000  9089
third             C           56    8000  8056
second            B           15    7000  7015
first             A           12    6000  6012

In [16]:
#select first row by index name
df.loc['first']

Student Name       A
Student Age       12
Salary          6000
new             6012
Name: first, dtype: object

In [17]:
#select first row by row name
df.iloc[0]

Student Name       D
Student Age       89
Salary          9000
new             9089
Name: four, dtype: object

In [18]:
## Select 2 & 3rd row
df.iloc[[1,2]]

       Student Name  Student Age  Salary   new
third             C           56    8000  8056
second            B           15    7000  7015

In [19]:
#Select 3rd row and column 'Name' and 'Age'
df.iloc[2,[0,1]]

Student Name     B
Student Age     15
Name: second, dtype: object

In [20]:
#Select 3rd,4th row and column 'Name' and 'Age'
df.iloc[[2,3],[0,1]]

       Student Name  Student Age
second            B           15
first             A           12

In [21]:
#Select 3rd,4th row and column 'Name' and 'Age'
df.loc[['third','four'],['Student Name','Student Age']]

      Student Name  Student Age
third            C           56
four             D           89

### 8.Drop Rows/Columns

DataFrame.drop(labels=None, *, axis=0, index=None, columns=None, level=None, inplace=False, errors='raise')

In [22]:
df.drop('third',axis=0)

       Student Name  Student Age  Salary   new
four              D           89    9000  9089
second            B           15    7000  7015
first             A           12    6000  6012

In [23]:
# axis=1: operation column wise
# axis=0 :operation row wise
#dataframe.drop(index label,axis=1)
df.drop('Student Age',axis=1)

       Student Name  Salary   new
four              D    9000  9089
third             C    8000  8056
second            B    7000  7015
first             A    6000  6012

In [62]:
df.columns

Index(['Student Name', 'Student Age', 'Salary', 'new'], dtype='object')

In [64]:
df.columns[0]

'Student Name'

In [65]:
df.describe()

       Student Age       Salary          new
count     4.000000     4.000000     4.000000
mean     43.000000  7500.000000  7543.000000
std      36.651512  1290.994449  1326.151072
min      12.000000  6000.000000  6012.000000
25%      14.250000  6750.000000  6764.250000
50%      35.500000  7500.000000  7535.500000
75%      64.250000  8250.000000  8314.250000
max      89.000000  9000.000000  9089.000000

In [67]:
type(df)

pandas.core.frame.DataFrame

### 9.Reset/ Set index

In [25]:
#Reset index
df.reset_index()

    index Student Name  Student Age  Salary   new
0    four            D           89    9000  9089
1   third            C           56    8000  8056
2  second            B           15    7000  7015
3   first            A           12    6000  6012

In [26]:
#set column same is the index
df.set_index('Student Name')

              Student Age  Salary   new
Student Name
D                      89    9000  9089
C                      56    8000  8056
B                      15    7000  7015
A                      12    6000  6012

### 10.Filter based on conditional operators

In [27]:
#condition:Return boolean result
df['Salary']>7000

four       True
third      True
second    False
first     False
Name: Salary, dtype: bool

In [28]:
#dataframe[condition]:Return only true row value
df[df['Salary']>7000]

      Student Name  Student Age  Salary   new
four             D           89    9000  9089
third            C           56    8000  8056

In [29]:
#Select salary and student name where salary >7000
df[df['Salary']>7000][['Salary','Student Name']]

       Salary Student Name
four     9000            D
third    8000            C

In [30]:
#select only those observation which salary >7000 and age >56
df[(df['Salary']>7000) & (df['Student Age'] >=15)]

      Student Name  Student Age  Salary   new
four             D           89    9000  9089
third            C           56    8000  8056

In [31]:
#select only those observation which salary >7000 or age >56
df[(df['Salary']>7000) | (df['Student Age'] >=15)]

       Student Name  Student Age  Salary   new
four              D           89    9000  9089
third             C           56    8000  8056
second            B           15    7000  7015

### Query function

In [32]:
df.query('Salary ==8000')

      Student Name  Student Age  Salary   new
third            C           56    8000  8056

In [33]:
df.query('Salary in [8000,7000]')

       Student Name  Student Age  Salary   new
third             C           56    8000  8056
second            B           15    7000  7015

In [34]:
df.query('Salary not in [8000,7000]')

      Student Name  Student Age  Salary   new
four             D           89    9000  9089
first            A           12    6000  6012

In [35]:
df.query('Salary >= 5000 & Salary <=8000')

       Student Name  Student Age  Salary   new
third             C           56    8000  8056
second            B           15    7000  7015
first             A           12    6000  6012

### 11.Missing Data

In [36]:
import numpy as np

In [37]:
d=pd.DataFrame({'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]})
d

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [38]:
#True/False for all value:if missing show True
d.isna()

       A      B      C
0  False  False  False
1  False   True  False
2   True   True  False

In [39]:
#Show Column wise which columns have nan values(even 1 nan is enough)
d.isna().any()

A     True
B     True
C    False
dtype: bool

In [40]:
#drop missing columns
d.dropna(axis=1)

   C
0  1
1  2
2  3

In [41]:
#drop missing row:(thresh=n)::Keep rows ,if atlest 'n' non-missing is there .
d.dropna(thresh=2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

#### Fill missing value
dataframe.fillna(value='fill')

In [42]:
d

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [43]:
#fill missing value with 0 value
d.fillna(value=0)

     A    B  C
0  1.0  5.0  1
1  2.0  0.0  2
2  0.0  0.0  3

In [44]:
#fill missing value with mean value in column 'A'
d['A'].fillna(value=d['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

### 12.Group by opration

In [45]:
Name=['A','B','A','C','B']
Salary=[1000,2000,4000,5000,600]
g=pd.DataFrame({'Name':Name,'Salary':Salary})
g

  Name  Salary
0    A    1000
1    B    2000
2    A    4000
3    C    5000
4    B     600

In [46]:
group=g.groupby('Name')

In [47]:
#Average Salary of each Name
group.mean()

      Salary
Name
A     2500.0
B     1300.0
C     5000.0

In [48]:
# Count of each Name
group.count()

      Salary
Name
A          2
B          2
C          1

In [49]:
# Sum of each Name
group.sum()

      Salary
Name
A       5000
B       2600
C       5000

In [50]:
group.describe()

     Salary
      count    mean          std     min     25%     50%     75%     max
Name
A       2.0  2500.0  2121.320344  1000.0  1750.0  2500.0  3250.0  4000.0
B       2.0  1300.0   989.949494   600.0   950.0  1300.0  1650.0  2000.0
C       1.0  5000.0          NaN  5000.0  5000.0  5000.0  5000.0  5000.0

### 13.Merging Concept : Concatation,Append,Merge,join

In [51]:
ID=[100,101,103,104,108]
Salary=[5000,6000,2000,4000,9000]
df1=pd.DataFrame({'ID':ID,'Salary':Salary})
df1

    ID  Salary
0  100    5000
1  101    6000
2  103    2000
3  104    4000
4  108    9000

In [52]:
ID=[100,101,105,107]
Age=[24,25,34,55]
df2=pd.DataFrame({'ID':ID,'Age':Age})
df2

    ID  Age
0  100   24
1  101   25
2  105   34
3  107   55

#### Concatation
concat(objs, axis=0, join='outer', join_axes=None, ignore_index=False, keys=None, levels=None, names=None, verify_integrity=False, sort=None, copy=True)

In [53]:
#Append data frames vertically
pd.concat([df1,df2],sort=False)

    ID  Salary   Age
0  100  5000.0   NaN
1  101  6000.0   NaN
2  103  2000.0   NaN
3  104  4000.0   NaN
4  108  9000.0   NaN
0  100     NaN  24.0
1  101     NaN  25.0
2  105     NaN  34.0
3  107     NaN  55.0

#### Merge function
merge(left, right, how='inner', on=None, left_on=None, right_on=None, left_index=False, right_index=False, sort=False, suffixes=('_x', '_y'), copy=True, indicator=False, validate=None)

how : {'left', 'right', 'outer', 'inner'}, default 'inner' Type of merge to be performed.

    * left: use only keys from left frame, similar to a SQL left outer join;
      preserve key order.
    * right: use only keys from right frame, similar to a SQL right outer join;
      preserve key order.
    * outer: use union of keys from both frames, similar to a SQL full outer
      join; sort keys lexicographically.
    * inner: use intersection of keys from both frames, similar to a SQL inner
      join; preserve the order of the left keys.

#### Left join

In [54]:
pd.merge(df1,df2,how='left',on='ID')

    ID  Salary   Age
0  100    5000  24.0
1  101    6000  25.0
2  103    2000   NaN
3  104    4000   NaN
4  108    9000   NaN

### Right join

In [55]:
pd.merge(df1,df2,how='right',on='ID')

    ID  Salary  Age
0  100  5000.0   24
1  101  6000.0   25
2  105     NaN   34
3  107     NaN   55

#### Join Function
join(other, on=None, how='left', lsuffix='', rsuffix='', sort=False)

how : {'left', 'right', 'outer', 'inner'}, default 'left' How to handle the operation of the two objects.

    * left: use calling frame's index (or column if on is specified)
    * right: use `other`'s index.
    * outer: form union of calling frame's index (or column if on isspecified) with `other`'s index, and sort it.
      lexicographically.
    * inner: form intersection of calling frame's index (or column ifon is specified) with `other`'s index, preserving              the order of the calling's one.

In [56]:
df1.join(df2,how='left',sort=True,lsuffix='_l',rsuffix='_r')

   ID_l  Salary   ID_r   Age
0   100    5000  100.0  24.0
1   101    6000  101.0  25.0
2   103    2000  105.0  34.0
3   104    4000  107.0  55.0
4   108    9000    NaN   NaN

In [57]:
df1.join(df2,how='inner',sort=True,lsuffix='_l',rsuffix='_r')

   ID_l  Salary  ID_r  Age
0   100    5000   100   24
1   101    6000   101   25
2   103    2000   105   34
3   104    4000   107   55

In [58]:
df1.merge(df2,how='inner', left_index=True, right_index=True, sort=True, suffixes=('_l', '_r'))

   ID_l  Salary  ID_r  Age
0   100    5000   100   24
1   101    6000   101   25
2   103    2000   105   34
3   104    4000   107   55

In [59]:
pd.merge(df1,df2,how='inner',on='ID')

    ID  Salary  Age
0  100    5000   24
1  101    6000   25